services:
  frontend:
    build:
      context: ./frontend
    image: ghcr.io/Mritunjay-Aditya/frontend:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:${WEB_SERVER_FORWARD_PORT:-9001}:80"

  signaling-server:
    build:
      context: ./signaling-server
    image: ghcr.io/Mritunjay-Aditya/signaling-server:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:9002:8001"
    deploy:
      resources:
        limits:
          memory: 2700M
